#!/bin/bash -l
#
# submit to slurm batch queue to run on DAV
#> module load slurm
#> sbatch batch_script
#> squeue -u $USER
#> scancel <ID> 
#
#SBATCH -J export_data
#SBATCH -n 8
#SBATCH -N 1
#SBATCH --ntasks-per-node=8
#SBATCH -t 04:00:00
#SBATCH -p dav
#SBATCH -o export_data.out.%J
#SBATCH -e export_data.out.%J
#SBATCH --account=P19010000
#SBATCH -C caldera

export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

module purge
module list
module load ncarenv
module load python
module list

echo "Begin Post-Processing Job"

date

cd /glade/u/home/fvitt/cesm_forecast_scripts

# --- Determine time-stamp/file-ID string ---
export LID="`date +%Y%m%d-%H%M%S`"

./export_data.py &> /glade/scratch/fvitt/GEOS5_frcst_data/export_data.log.$LID

echo "End Post-Processing Job"
date
exit 0
